### ISSUE TITLE
MzML file parsing exception

### ISSUE THREAD

**Issue by KenWifi** [msdk/msdk#249]
Hi,

Recent days, I tried to get TIC information form mzML file by msdk package, but I met an exception when I parsed it. My codes as follow:
`MzMLFileImportMethod mzMLFileImportMethod = new MzMLFileImportMethod(spectrumFilePath);

            try {
                mzMLFileImportMethod.execute();
            } catch (MSDKException e) {
                e.printStackTrace();
            }

            MzMLRawDataFile mzMLRawDataFile = (MzMLRawDataFile) mzMLFileImportMethod.getResult();
            for (Chromatogram chromatogram : mzMLRawDataFile.getChromatograms()){
                   System.out.println(Arrays.toString(chromatogram.getIntensityValues()));
            }` 

And this is exception:
`Exception in thread "main" io.github.msdk.MSDKRuntimeException: java.lang.ArrayIndexOutOfBoundsException: -1
	at io.github.msdk.io.mzml.data.MzMLChromatogram.getIntensityValues(MzMLChromatogram.java:419)
	at io.github.msdk.datamodel.Chromatogram.getIntensityValues(Chromatogram.java:94)
	at PSMviewer.fileimport.MSOneImport.parseSpectrum(MSOneImport.java:106)
	at PSMviewer.fileimport.MSOneImport.<init>(MSOneImport.java:69)
	at PSMviewer.fileimport.MSOneImport.main(MSOneImport.java:56)
Caused by: java.lang.ArrayIndexOutOfBoundsException: -1
	at io.github.msdk.io.mzml.util.ByteBufferInputStream.byteBuffer(ByteBufferInputStream.java:137)
	at io.github.msdk.io.mzml.util.ByteBufferInputStream.position(ByteBufferInputStream.java:255)
	at io.github.msdk.io.mzml.util.ByteBufferInputStream.constrain(ByteBufferInputStream.java:274)
	at io.github.msdk.io.mzml.data.MzMLPeaksDecoder.decodeToFloat(MzMLPeaksDecoder.java:59)
	at io.github.msdk.io.mzml.data.MzMLChromatogram.getIntensityValues(MzMLChromatogram.java:417)
	... 4 more`

**Comment by KenWifi** [comment]
When I generated mzML file again in 32-bit encoding, it works! I converted mzML by “MSConvertGUI” and my raw file format is "Thermo" .raw.

**Comment by nilshoffmann** [comment]
Looks like an issue with the current code, since we do not check the actual encoding of the data but simply expect intensity values to be encoded as 32 bit floats: 

https://github.com/msdk/msdk/blob/cd333dcfe38c50d16ede27b445cbb7f7d3a02f06/msdk-io-mzml/src/main/java/io/github/msdk/io/mzml/data/MzMLChromatogram.java#L417

**Comment by KaiLiCn** [comment]
I guess it's not hard to support 64 bit encoding. :)

**Comment by adhi1419** [comment]
@nilshoffmann That is not the case. We do check for the precision of encoded data within the _decodeFloat()_ method
https://github.com/msdk/msdk/blob/cd333dcfe38c50d16ede27b445cbb7f7d3a02f06/msdk-io-mzml/src/main/java/io/github/msdk/io/mzml/data/MzMLPeaksDecoder.java#L129

The issue could be arising from elsewhere. This seems to be arising due to an error in constraining the _InputStream_ to only the encoded Intensity Array.

**Comment by tomas-pluskal** [comment]
@KenWifi , could you send an example file that caused the exception, e.g. via DropBox?

**Comment by KenWifi** [comment]
@tomas-pluskal, sure, but I need to find the data and send to you ASAP.

**Comment by KaiLiCn** [comment]
@tomas-pluskal https://www.dropbox.com/s/kydqej3gu690a64/64bitmzML.rar?dl=0 There are raw file and mzML file in the package. I wish it could help you.

**Comment by KaiLiCn** [comment]
@tomas-pluskal https://www.dropbox.com/s/kydqej3gu690a64/64bitmzML.rar?dl=0 There are raw file and mzML file in the package. I wish it could help you. KenWifi is my another account, I forgot to change it. Sorry about it~
