### ISSUE TITLE
MsSpectrumDataPointList object

### ISSUE THREAD

**Issue by SandraCastilloPriego** [msdk/msdk#48]
Hi,
I've notice some strange behaviour with this object, maybe I'm doing something wrong? Here it is:

// I create the data point list and fill it
MsSpectrumDataPointList dataPoints = MSDKObjectBuilder.getMsSpectrumDataPointList();      
scan.getDataPoints(dataPoints);

// I transform it into a List
List<MsIon> ionList = Lists.newArrayList(dataPoints.iterator());

System.out.println(dataPoints.getSize()); // It gives me 426
System.out.println(ionList.size()); //It gives me 425

Shouldn't they be equal? What is happening?

**Comment by tomas-pluskal** [comment]
Hi Sandra, 

it's possible you found a bug :) The iterator() function of the MsSpectrumDataPointList is not really tested. I'll take a look at it.

**Comment by tomas-pluskal** [comment]
I fixed the getSize() bug in pull request #49. However, your approach of copying the data points using the iterator is not going to work. The reason is in the way how the iterator is implemented - it traverses the existing m/z and intensity arrays and updates only a pointer to the position in the array. Since no new objects are created during the iteration (to save memory), your final ArrayList will end up having the same object in all positions.

**Comment by SandraCastilloPriego** [comment]
Hi,
yes, I've realized already :)
